apiVersion: v1
entries:
  postgres:
  - apiVersion: v2
    appVersion: "13.12"
    created: "2026-01-06T18:45:52.554038-06:00"
    description: Postgres helm chart for Kubernetes
    digest: 7d690b1aaa654ba27f6ae58669f40a95e7f6a92231365e87d2daa7354690333e
    home: https://github.com/rbg/postgres-helm
    icon: https://raw.githubusercontent.com/rbg/postgres-helm/master/helm/postgres.png
    keywords:
    - postgres
    maintainers:
    - email: rbg@openrbg.com
      name: rbg
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: postgres
    sources:
    - https://github.com/rbg/postgres-helm
    type: application
    urls:
    - postgres-0.1.1.tgz
    version: 0.1.1
generated: "2026-01-06T18:45:52.553647-06:00"
