apiVersion: v2
name: postgres
description: Postgres helm chart for Kubernetes
home: https://github.com/rbg/postgres-helm
icon: https://raw.githubusercontent.com/rbg/postgres-helm/master/helm/postgres.png
keywords:
- postgres
maintainers:
- email: rbg@openrbg.com
  name: rbg
- email: hans.erik.heggem@gmail.com
  name: hansehe
sources:
- https://github.com/rbg/postgres-helm

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "13.12"
